- id: fmt
  name: cargo fmt
  description: Format all Rust files with rustfmt.
  entry: cargo fmt
  language: rust
  types: [rust]
  args: ["--"]

- id: check
  name: cargo check
  description: Check the package for errors.
  entry: cargo check
  language: rust
  types: [rust]
  pass_filenames: false

- id: clippy
  name: cargo clippy
  description: Lint Rust sources.
  entry: cargo clippy
  language: rust
  args: ["--", "-D", "warnings"]
  types: [rust]
  pass_filenames: false
